package MCalculadora;


/**
* MCalculadora/ICalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* viernes 3 de marzo de 2023 23H31' CET
*/

public interface ICalculadoraOperations 
{
  int sumar (MCalculadora.Operadores Ops);
  int restar (MCalculadora.Operadores Ops);
  int multiplicar (MCalculadora.Operadores Ops);
  int dividir (MCalculadora.Operadores Ops);
  int exponencial (MCalculadora.Operadores Ops);
  int logNeperiano (MCalculadora.Operadores Ops);
  int modulo (MCalculadora.Operadores Ops);
} // interface ICalculadoraOperations
